// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextBase_Adventure.Utility;

#nullable disable

namespace TextBase_Adventure.Migrations
{
    [DbContext(typeof(DataContextUtility))]
    [Migration("20240904095740_SaveMigration")]
    partial class SaveMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TextBase_Adventure.Models.Save", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("saves");
                });
#pragma warning restore 612, 618
        }
    }
}
